package com.piedpiper.swerve.lexer;

// keep the name values of tokens restricted to what is in this enum rather than have it be a string which could be any value
public enum TokenType {
    NUMBER,
    OP,
    ID,
    STRING,
    LEFT_CB,
    RIGHT_CB,
    LEFT_PAREN,
    RIGHT_PAREN,
    LEFT_SQB,
    RIGHT_SQB,
    SC,
    COLON,
    COMMA,
    KW_CONST,
    KW_INT,
    KW_DOUBLE,
    KW_STR,
    KW_BOOL,
    KW_PROTO,
    KW_GEN,
    KW_FN,
    KW_RET,
    KW_FOR,
    KW_IF,
    KW_ELSE,
    KW_WHILE,
    KW_BRK,
    KW_CNT,
    KW_TRUE,
    KW_FALSE,
    KW_ARR,
    KW_NULL
}
